#!/usr/bin/env python

Import("env")
Import("env_modules")

env_tilemap3d = env_modules.Clone()

env_tilemap3d.Prepend(CPPPATH=["."])

env_tilemap3d.add_source_files(env.modules_sources, "plugin/*.cpp")
env_tilemap3d.add_source_files(env.modules_sources, "*.cpp")